services:

  postgres:
    image: postgres:15
    environment:
#      POSTGRES_DB: mydb
      POSTGRES_USER: microservice
      POSTGRES_PASSWORD: 123369
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecom
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ecom
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASSWORD: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecom
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_container
    ports:
      - "9411:9411"
    networks:
      - ecom
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - ecom
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin:

networks:
  ecom:
    driver: bridge