services:

  postgres:
    image: postgres:15
    environment:
#      POSTGRES_DB: mydb
      POSTGRES_USER: microservice
      POSTGRES_PASSWORD: 123369
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecom

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ecom

volumes:
  postgres_data:
  pgadmin:

networks:
  ecom: