spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/products/**
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/users/**
            - id: order-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**, /api/cart/**
server:
  port: 8080


