
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
      database: userdb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "refresh,busrefresh"

server:
  port: 8082